server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: book-route
          uri: http://localhost:8000
          predicates:
            - Path=/books/**
