server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: book-route
          uri: http://localhost:8000
          predicates:
            - Path=/books/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway-service
            client-secret: npRcIXlq9jMHFmnAJD2Sle6JZSEgNVtf
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/PolarBookshop
